export const LOGIN = "LOGIN";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGOUT = "LOGOUT";

export const SET_TOKENS = 'SET_TOKENS'

export const GET_SKILLS = "GET_SKILLS";
export const GET_SKILLS_COMPLETED = "GET_SKILLS_COMPLETED";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const CREATE_SKILL = "CREATE_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";

export const GET_WORKERS = "GET_WORKERS";
export const GET_WORKERS_COMPLETED = "GET_WORKERS_COMPLETED";
export const UPDATE_WORKER = "UPDATE_WORKER";
export const CREATE_WORKER = "CREATE_WORKER";
export const DELETE_WORKER = "DELETE_WORKER";

export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICES_COMPLETED = "GET_SERVICES_COMPLETED";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const CREATE_SERVICE = "CREATE_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";

export const GET_SERVICE_TYPES = "GET_SERVICE_TYPES";
export const GET_SERVICE_TYPES_COMPLETED = "GET_SERVICE_TYPES_COMPLETED";
export const UPDATE_SERVICE_TYPE = "UPDATE_SERVICE_TYPE";
export const CREATE_SERVICE_TYPE = "CREATE_SERVICE_TYPE";
export const DELETE_SERVICE_TYPE = "DELETE_SERVICE_TYPE";
