# Generated by Django 5.2 on 2025-08-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderedservicebyclient_custom_commission_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_client_b2b',
            new_name='client_b2b',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_client_b2c',
            new_name='client_b2c',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_services',
            new_name='services',
        ),
    ]
