# Generated by Django 5.2 on 2025-05-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='worker_type',
        ),
    ]
