# Generated by Django 5.2 on 2025-05-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_remove_worker_worker_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerType',
        ),
    ]
