# Generated by Django 5.2 on 2025-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_worker_user_alter_worker_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='skills',
            field=models.ManyToManyField(related_name='workers', to='workers.skill'),
        ),
    ]
