# Generated by Django 5.2 on 2025-05-08 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('default_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='services', to='workers.skill')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
