# Generated by Django 5.2 on 2025-05-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='default_commission_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
