# Generated by Django 5.2 on 2025-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_default_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
    ]
