# Generated by Django 5.2 on 2025-05-08 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientB2CServiceCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Commissions for B2C Clients',
                'ordering': ['client_b2c'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='clientb2bservicecommission',
            name='unique_client_service',
        ),
        migrations.AddConstraint(
            model_name='clientb2bservicecommission',
            constraint=models.UniqueConstraint(fields=('client_b2b', 'service'), name='unique_client_b2b_service'),
        ),
        migrations.AddField(
            model_name='clientb2cservicecommission',
            name='client_b2c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientb2c'),
        ),
        migrations.AddField(
            model_name='clientb2cservicecommission',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddConstraint(
            model_name='clientb2cservicecommission',
            constraint=models.UniqueConstraint(fields=('client_b2c', 'service'), name='unique_client_b2c_service'),
        ),
    ]
