# Generated by Django 5.2 on 2025-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientb2cservicecommission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientb2b',
            name='company_address',
        ),
        migrations.AddField(
            model_name='clientb2b',
            name='company_address_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientb2b',
            name='company_address_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientb2c',
            name='client_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
            preserve_default=False,
        ),
    ]
