# Generated by Django 5.2 on 2025-05-15 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustomprofile',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usercustomprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usercustomprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usercustomprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usercustomprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usercustomprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='usercustomprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercustomprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('WORKER', 'Worker')], default='WORKER', max_length=20),
        ),
        migrations.AddField(
            model_name='usercustomprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercustomprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usercustomprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usercustomprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
