# Generated by Django 5.2 on 2025-06-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderedservicebyclient_custom_commission_percentage_and_more'),
        ('workers', '0005_alter_worker_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderedservicebyclient')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
            options={
                'unique_together': {('worker', 'ordered_service')},
            },
        ),
    ]
